[package]
name = "cos-proto-api"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
tonic.workspace = true
prost.workspace = true
cos-proto-reconciler.path = "../../crates/cos-proto-reconciler"
serde_json = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["std", "derive"] }
anyhow.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
