syntax = "proto3";

package containeros.api.v1;

service ApiService {
  rpc ConfigValidate(ConfigValidateRequest) returns (ConfigValidateResponse) {}
  rpc ConfigPush(ConfigPushRequest) returns (ConfigPushResponse) {}
  rpc ConfigPull(ConfigPullRequest) returns (ConfigPullResponse) {}
  rpc FsWrite(FsWriteRequest) returns (FsWriteResponse) {}
  rpc FsList(FsListRequest) returns (FsListResponse) {}
  rpc FsRead(FsReadRequest) returns (FsReadResponse) {}
  rpc ResourcesList(ResourcesListRequest) returns (ResourcesListResponse) {}
  rpc ResourcesGet(ResourcesGetRequest) returns (ResourcesGetResponse) {}
  rpc ResourcesReconcileNow(ResourcesReconcileNowRequest) returns (ResourcesReconcileNowResponse) {}
  rpc ResourcesForceDelete(ResourcesForceDeleteRequest) returns (ResourcesForceDeleteResponse) {}
  rpc SystemReboot(SystemRebootRequest) returns (SystemRebootResponse) {}
}

message ConfigValidateRequest {
  bytes raw = 1;
}

message ConfigValidateResponse {
  bytes raw = 1;
}

message ConfigPushRequest {
  bytes raw = 1;
}

message ConfigPushResponse {
  bytes raw = 1;
}

message ConfigPullRequest {
  bytes raw = 1;
}

message ConfigPullResponse {
  bytes raw = 1;
}

message FsWriteRequest {
  bytes raw = 1;
}

message FsWriteResponse {
  bytes raw = 1;
}

message FsListRequest {
  bytes raw = 1;
}

message FsListResponse {
  bytes raw = 1;
}

message FsReadRequest {
  bytes raw = 1;
}

message FsReadResponse {
  bytes raw = 1;
}

message ResourcesListRequest {
  bytes raw = 1;
}

message ResourcesListResponse {
  bytes raw = 1;
}

message ResourcesGetRequest {
  bytes raw = 1;
}

message ResourcesGetResponse {
  bytes raw = 1;
}

message ResourcesReconcileNowRequest {
  bytes raw = 1;
}

message ResourcesReconcileNowResponse {
  bytes raw = 1;
}

message ResourcesForceDeleteRequest {
  bytes raw = 1;
}

message ResourcesForceDeleteResponse {
  bytes raw = 1;
}

message SystemRebootRequest {
  bytes raw = 1;
}

message SystemRebootResponse {
  bytes raw = 1;
}
