#!/usr/bin/env -S just --justfile

set dotenv-load

typst-bin := "typst"
typst-args := "--root . --ignore-system-fonts --font-path ./lib/fonts/alegreya-sans:./lib/fonts/liberation"
typstyle-bin := "typstyle"
typstyle-args := "--line-width 80 --indent-width 4 --wrap-text"

[private]
_output-suffix := "_Arroyo_Gluck_2026.pdf"

subject-statement-output := "Enonce_LOG_diplome" + _output-suffix
thesis-output := "ISC_LOG_memoire_diplome" + _output-suffix
poster-output := "ISC_LOG_poster_diplome" + _output-suffix
abstract-output := "ISC_LOG_resume_diplome" + _output-suffix
slides-prefix := "ISC_LOG_slides"

@help:
    just --list

check: _spelling
    {{ typstyle-bin }} {{ typstyle-args }} --check ./

fix:
    {{ typstyle-bin }} {{ typstyle-args }} --inplace ./

build: _outdir (_build-slide "handout-16-9") _build-slides
    {{ typst-bin }} compile {{ typst-args }} subject-statement/main.typ output/{{ subject-statement-output }}
    {{ typst-bin }} compile {{ typst-args }} abstract/main.typ output/{{ abstract-output }}
    {{ typst-bin }} compile {{ typst-args }} poster/main.typ output/{{ poster-output }}
    {{ typst-bin }} compile {{ typst-args }} thesis/main.typ output/{{ thesis-output }}

clean:
    rm -rf ./output/
    find . -name "*.pdf" -delete

[private]
[working-directory(invocation_directory())]
_spelling:
    cspell lint "./docs/internal/**/*.typ"

[private]
_outdir:
    mkdir -p output/slides/

[private]
_build-slide slide:
    {{ typst-bin }} compile {{ typst-args }} slides/formats/slides-{{ slide }}.typ output/slides/{{ slides-prefix }}_{{ slide }}{{ _output-suffix }}

[private]
[parallel]
_build-slides: (_build-slide "handout-16-10") (_build-slide "handout-4-3") (_build-slide "presentation-16-10") (_build-slide "presentation-16-9") (_build-slide "presentation-4-3") (_build-slide "pympress-16-10") (_build-slide "pympress-16-9") (_build-slide "pympress-4-3")

