#!/usr/bin/env -S just --justfile

set dotenv-load

[private]
_docker := env("JUST_CONTAINER_RUNTIME", "docker")

[private]
_docker-args := "run --rm -v " + module_directory() + ":/work -v typst-cache:/root/.cache/typst --entrypoint '' -w /work "

[private]
_docker-typst-image := "docker.io/pandoc/typst:3.9.0.2@sha256:8b88646589ec8aa05afdca02dbe6849fa38f3235fb23559970ba82088a5d8f75"

[private]
_docker-typstyle-image := "docker.io/fredericarr/typstyle:latest"

[private]
_typst-args := "--root . --ignore-system-fonts --font-path ./lib/fonts/alegreya-sans:./lib/fonts/liberation"

[private]
_typst-cc := "typst compile " + _typst-args

[private]
_typst-runner := _docker + " " + _docker-args + " " + _docker-typst-image + " " + _typst-cc

[private]
_typstyle-args := "--line-width 80 --indent-width 4 --wrap-text"

[private]
_typstyle-cc := "typstyle " + _typstyle-args

[private]
_typstyle-runner := _docker + " " + _docker-args + " " + _docker-typstyle-image + " " + _typstyle-cc

[private]
_output-suffix := "_Arroyo_Gluck_2026.pdf"

[private]
_subject-statement-output := "Enonce_LOG_diplome" + _output-suffix

[private]
_thesis-output := "Rapport_Intermediare" + _output-suffix
# _thesis-output := "ISC_LOG_memoire_diplome" + _output-suffix

[private]
_poster-output := "ISC_LOG_poster_diplome" + _output-suffix

[private]
_abstract-output := "ISC_LOG_resume_diplome" + _output-suffix

@help:
    just --list

check: format lint

fix: format-fix

[private]
format:
    {{ _typstyle-runner }} --check ./

[private]
format-fix:
    {{ _typstyle-runner }} --inplace ./

[private]
lint:
    {{ _typstyle-runner }} --diff ./

build: _build-slides-warmup _build-slides
    {{ _typst-runner }} subject-statement/main.typ output/{{ _subject-statement-output }}
    {{ _typst-runner }} abstract/main.typ output/{{ _abstract-output }}
    {{ _typst-runner }} poster/main.typ output/{{ _poster-output }}
    {{ _typst-runner }} thesis/main.typ output/{{ _thesis-output }}

clean:
    rm -rf ./output/
    find . -name "*.pdf" -delete

[private]
_cs slide: _outdir
    {{ _typst-runner }} slides/formats/slides-{{ slide }}.typ output/slides/slides-{{ slide }}{{ _output-suffix }}

[private]
_outdir:
    mkdir -p output/slides/

[private]
_build-slides-warmup: (_cs "handout-16-9")

[private]
[parallel]
_build-slides: (_cs "handout-16-10") (_cs "handout-16-9") (_cs "handout-4-3") (_cs "presentation-16-10") (_cs "presentation-16-9") (_cs "presentation-4-3") (_cs "pympress-16-10") (_cs "pympress-16-9") (_cs "pympress-4-3")
