image:
  name: docker.io/nixos/nix:2.32.8@sha256:080e6df285c98b2ea34080bf3762308288e73d7f4012e3bcf96bb98911a24311
  entrypoint: [ '/bin/sh', '-c' ]

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

stages:
  - check
  - build

check-docs-internal:
  stage: check
  script: nix develop -c just docs check

build-docs-internal:
  stage: build
  script:
    - nix develop -c just docs build
    - cp -r docs/internal/output/ ./output/
  artifacts:
    when: on_success
    access: all
    name: documents
    expire_in: 7 days
    paths: [output/**/*.pdf]
  needs: [check-docs-internal]
