stages:
  - lint
  - build

lint-docs-internal:
  stage: lint
  script: just docs check
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH =~ /^ci\/.*$/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - when: manual

build-docs-internal:
  stage: build
  script:
    - just docs build
    - cp -r docs/internal/output/ ./output/
  artifacts:
    when: on_success
    access: all
    name: documents
    expire_in: 7 days
    paths: [output/**/*.pdf]
  needs: [lint-docs-internal]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH =~ /^ci\/.*$/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - when: manual
