[workspace]
resolver = "3"
members = ["cmd/*", "crates/*"]

[workspace.lints.rust]
ambiguous_negative_literals = "warn"
unused_mut = "warn"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
similar_names = "allow"
# Restrictions
allow_attributes = "deny"
# arbitrary_source_item_ordering = "deny" # TODO: Add (?)
arithmetic_side_effects = "deny"
as_conversions = "deny"
as_pointer_underscore = "deny"
as_underscore = "deny"
assertions_on_result_states = "deny"
big_endian_bytes = "deny"
cfg_not_test = "deny"
clone_on_ref_ptr = "deny"
cognitive_complexity = "deny"
exit = "deny"
expect_used = "deny"
get_unwrap = "deny"
if_then_some_else_none = "deny"
impl_trait_in_params = "deny"
indexing_slicing = "deny"
infinite_loop = "deny"
inline_trait_bounds = "deny"
map_with_unused_argument_over_ranges = "deny"
mixed_read_write_in_expression = "deny"
needless_raw_strings = "deny"
non_ascii_literal = "deny"
non_zero_suggestions = "deny"
panic = "deny"
panic_in_result_fn = "deny"
pathbuf_init_then_push = "deny"
precedence_bits = "deny"
print_stderr = "deny"
print_stdout = "deny"
redundant_test_prefix = "deny"
redundant_type_annotations = "deny"
ref_patterns = "deny"
rest_pat_in_fully_bound_structs = "deny"
# unnecessary_rest_pattern = "deny"
# rest_pattern_accessible_field = "deny"
return_and_then = "deny"
semicolon_inside_block = "deny"
unseparated_literal_suffix = "deny"
single_char_lifetime_names = "deny"
str_to_string = "deny"
string_add = "deny"
string_lit_chars_any = "deny"
suspicious_xor_used_as_pow = "deny"
tests_outside_test_module = "deny"
try_err = "deny"
unnecessary_safety_comment = "deny"
unnecessary_safety_doc = "deny"
unnecessary_self_imports = "deny"
# unneeded_field_pattern = "deny"
unused_async = "allow"
unused_result_ok = "deny"
unused_trait_names = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"
missing_const_for_fn = "allow"
unnecessary_wraps = "allow"
unused_async_trait_impl = "allow"
# TODO: Check before release
# use_debug = "deny"
# unreachable = "deny"
# unimplemented = "deny"
# todo = "deny"
# dbg_macro = "deny"
## Documentation
doc_include_without_cfg = "deny"
doc_paragraphs_missing_punctuation = "deny"
undocumented_unsafe_blocks = "deny"
# missing_docs_in_private_items = "allow" # TODO: Add
missing_panics_doc = "allow" # TODO: Remove
missing_errors_doc = "allow" # TODO: Remove

[workspace.lints.cargo]
pedantic = "warn"
nursery = "warn"
non_kebab_case_packages = "forbid"
non_kebab_case_features = "forbid"

[workspace.dependencies]
rustix = { version = "1.1.4", default-features = false }
# rand = { version = "0.10.1", default-features = false }
tempfile = { version = "3.27.0", default-features = false }
serde = { version = "1.0.228", default-features = false }
serde_json = { version = "1.0.150", default-features = false }
smol = { version = "2.0.2", default-features = false }
anyhow = { version = "1.0.103", default-features = false }
# rtnetlink = { version = "0.21.0", default-features = false }
# derive_builder = { version = "0.20.2", default-features = false }
# futures-lite = { version = "2.6.1", default-features = false }
# ipnet = { version = "2.12.0", default-features = false }
bitflags = { version = "2.13.0", default-features = false }
libc = { version = "0.2.186", default-features = false }
# loopdev-3 = { version = "0.5.3", default-features = false }
# quote = { version = "1.0.45", default-features = false }
# syn = { version = "2.0.118", default-features = false }
# nix = { version = "0.31.3", default-features = false }
# memmap2 = { version = "0.9.11", default-features = false }
sha3 = { version = "0.12.0", default-features = false }
# chrono = { version = "0.4.45", default-features = false }
tokio = { version = "1.52.3", default-features = false }
# itertools = { version = "0.15.0", default-features = false }
# futures = { version = "0.3.32", default-features = false }
prost = { version = "0.14.3", default-features = false }
# prost-types = { version = "0.14.3", default-features = false }
tonic = { version = "0.14.6", default-features = false }
tonic-prost = { version = "0.14.6", default-features = false }
tonic-prost-build = { version = "0.14.6", default-features = false }
# tokio-util = { version = "0.7.18", default-features = false }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false }
