CONFIG_SQUASHFS=y
CONFIG_OVERLAY_FS=y
CONFIG_MEMCG=y
CONFIG_SECURITYFS=y
CONFIG_BPF_SYSCALL=y
CONFIG_CGROUP_BPF=y

###########

CONFIG_VETH=y
CONFIG_BRIDGE=y

CONFIG_NF_TABLES=y
CONFIG_NF_TABLES_INET=y

CONFIG_NFT_CT=y
CONFIG_NFT_MASQ=y
CONFIG_NFT_NAT=y

CONFIG_NFT_FIB_INET=y
CONFIG_NFT_FIB_IPV4=y
CONFIG_NFT_FIB_IPV6=y
