[package]
name = "cos-proto-state-server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
cos-proto-state.path = "../cos-proto-state"
tonic = { workspace = true, features = ["codegen"] }
tonic-prost.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
