[package]
name = "network-controller"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bitflags = { workspace = true, features = ["std", "serde"] }
serde = { workspace = true, features = ["std", "derive"] }
sha3 = { workspace = true, features = ["alloc"] }
rustix = { workspace = true, features = [
    "std",
    "fs",
    "mm",
    "thread",
    "process",
] }
libc.workspace = true
system-controller.path = "../system-controller"
cos-proto-reconciler.path = "../../crates/cos-proto-reconciler"
cos-proto-reconciler-server.path = "../../crates/cos-proto-reconciler-server"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace = true, features = ["transport", "router"] }
serde_json = { workspace = true, features = ["std"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["std", "fmt", "ansi"] }
derive_builder = { workspace = true, features = ["std"] }
rtnetlink = { workspace = true, features = ["tokio_socket"] }
futures.workspace = true

[dev-dependencies]
isolation.path = "../../crates/isolation"
tempfile.workspace = true
smol.workspace = true
