syntax = "proto3";

package containeros.shared.v1;

message Identity {
  string schema = 1;
  string name = 2;
}

enum ResourceStatus {
  RESOURCE_STATUS_UNSPECIFIED = 0;
  RESOURCE_STATUS_RUNNING = 1;
  RESOURCE_STATUS_DELETING = 2;
}

message ResourceMeta {
  Identity id = 1;
  repeated Identity children = 2;
  ResourceStatus status = 3;
  bytes spec = 4;
  bytes state = 5;
}

message UserConfigResource {
  ResourceMeta meta = 1;
}

message DynamicResource {
  ResourceMeta meta = 1;
  Identity owner = 2;

  repeated Identity dependencies = 3;
  repeated Identity dependents = 4;
}

message MetaResource {
  oneof resource_type {
    UserConfigResource user_config = 1;
    DynamicResource dynamic = 2;
  }
}
