// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/containeros/api/v1/service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValidateRequest) Reset() {
	*x = ConfigValidateRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValidateRequest) ProtoMessage() {}

func (x *ConfigValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValidateRequest.ProtoReflect.Descriptor instead.
func (*ConfigValidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigValidateRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ConfigValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValidateResponse) Reset() {
	*x = ConfigValidateResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValidateResponse) ProtoMessage() {}

func (x *ConfigValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValidateResponse.ProtoReflect.Descriptor instead.
func (*ConfigValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigValidateResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ConfigPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPushRequest) Reset() {
	*x = ConfigPushRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPushRequest) ProtoMessage() {}

func (x *ConfigPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPushRequest.ProtoReflect.Descriptor instead.
func (*ConfigPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigPushRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ConfigPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPushResponse) Reset() {
	*x = ConfigPushResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPushResponse) ProtoMessage() {}

func (x *ConfigPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPushResponse.ProtoReflect.Descriptor instead.
func (*ConfigPushResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigPushResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ConfigPushStrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaml          string                 `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPushStrRequest) Reset() {
	*x = ConfigPushStrRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPushStrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPushStrRequest) ProtoMessage() {}

func (x *ConfigPushStrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPushStrRequest.ProtoReflect.Descriptor instead.
func (*ConfigPushStrRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigPushStrRequest) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type ConfigPushStrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPushStrResponse) Reset() {
	*x = ConfigPushStrResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPushStrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPushStrResponse) ProtoMessage() {}

func (x *ConfigPushStrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPushStrResponse.ProtoReflect.Descriptor instead.
func (*ConfigPushStrResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigPushStrResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ConfigPullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPullRequest) Reset() {
	*x = ConfigPullRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPullRequest) ProtoMessage() {}

func (x *ConfigPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPullRequest.ProtoReflect.Descriptor instead.
func (*ConfigPullRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigPullRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ConfigPullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPullResponse) Reset() {
	*x = ConfigPullResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPullResponse) ProtoMessage() {}

func (x *ConfigPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPullResponse.ProtoReflect.Descriptor instead.
func (*ConfigPullResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigPullResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FsWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsWriteRequest) Reset() {
	*x = FsWriteRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsWriteRequest) ProtoMessage() {}

func (x *FsWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsWriteRequest.ProtoReflect.Descriptor instead.
func (*FsWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *FsWriteRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FsWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsWriteResponse) Reset() {
	*x = FsWriteResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsWriteResponse) ProtoMessage() {}

func (x *FsWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsWriteResponse.ProtoReflect.Descriptor instead.
func (*FsWriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *FsWriteResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsListRequest) Reset() {
	*x = FsListRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsListRequest) ProtoMessage() {}

func (x *FsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsListRequest.ProtoReflect.Descriptor instead.
func (*FsListRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *FsListRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsListResponse) Reset() {
	*x = FsListResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsListResponse) ProtoMessage() {}

func (x *FsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsListResponse.ProtoReflect.Descriptor instead.
func (*FsListResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *FsListResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsReadRequest) Reset() {
	*x = FsReadRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsReadRequest) ProtoMessage() {}

func (x *FsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsReadRequest.ProtoReflect.Descriptor instead.
func (*FsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *FsReadRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsReadResponse) Reset() {
	*x = FsReadResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsReadResponse) ProtoMessage() {}

func (x *FsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsReadResponse.ProtoReflect.Descriptor instead.
func (*FsReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *FsReadResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesListRequest) Reset() {
	*x = ResourcesListRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesListRequest) ProtoMessage() {}

func (x *ResourcesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesListRequest.ProtoReflect.Descriptor instead.
func (*ResourcesListRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *ResourcesListRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesListResponse) Reset() {
	*x = ResourcesListResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesListResponse) ProtoMessage() {}

func (x *ResourcesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesListResponse.ProtoReflect.Descriptor instead.
func (*ResourcesListResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResourcesListResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesGetRequest) Reset() {
	*x = ResourcesGetRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesGetRequest) ProtoMessage() {}

func (x *ResourcesGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesGetRequest.ProtoReflect.Descriptor instead.
func (*ResourcesGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *ResourcesGetRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesGetResponse) Reset() {
	*x = ResourcesGetResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesGetResponse) ProtoMessage() {}

func (x *ResourcesGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesGetResponse.ProtoReflect.Descriptor instead.
func (*ResourcesGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *ResourcesGetResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesReconcileNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesReconcileNowRequest) Reset() {
	*x = ResourcesReconcileNowRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesReconcileNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesReconcileNowRequest) ProtoMessage() {}

func (x *ResourcesReconcileNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesReconcileNowRequest.ProtoReflect.Descriptor instead.
func (*ResourcesReconcileNowRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *ResourcesReconcileNowRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesReconcileNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesReconcileNowResponse) Reset() {
	*x = ResourcesReconcileNowResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesReconcileNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesReconcileNowResponse) ProtoMessage() {}

func (x *ResourcesReconcileNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesReconcileNowResponse.ProtoReflect.Descriptor instead.
func (*ResourcesReconcileNowResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *ResourcesReconcileNowResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesForceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesForceDeleteRequest) Reset() {
	*x = ResourcesForceDeleteRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesForceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesForceDeleteRequest) ProtoMessage() {}

func (x *ResourcesForceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesForceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ResourcesForceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *ResourcesForceDeleteRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ResourcesForceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesForceDeleteResponse) Reset() {
	*x = ResourcesForceDeleteResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesForceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesForceDeleteResponse) ProtoMessage() {}

func (x *ResourcesForceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesForceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ResourcesForceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{21}
}

func (x *ResourcesForceDeleteResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type SystemRebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemRebootRequest) Reset() {
	*x = SystemRebootRequest{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemRebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemRebootRequest) ProtoMessage() {}

func (x *SystemRebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemRebootRequest.ProtoReflect.Descriptor instead.
func (*SystemRebootRequest) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{22}
}

func (x *SystemRebootRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type SystemRebootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemRebootResponse) Reset() {
	*x = SystemRebootResponse{}
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemRebootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemRebootResponse) ProtoMessage() {}

func (x *SystemRebootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_containeros_api_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemRebootResponse.ProtoReflect.Descriptor instead.
func (*SystemRebootResponse) Descriptor() ([]byte, []int) {
	return file_proto_containeros_api_v1_service_proto_rawDescGZIP(), []int{23}
}

func (x *SystemRebootResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_proto_containeros_api_v1_service_proto protoreflect.FileDescriptor

const file_proto_containeros_api_v1_service_proto_rawDesc = "" +
	"\n" +
	"&proto/containeros/api/v1/service.proto\x12\x12containeros.api.v1\")\n" +
	"\x15ConfigValidateRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"*\n" +
	"\x16ConfigValidateResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"%\n" +
	"\x11ConfigPushRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"&\n" +
	"\x12ConfigPushResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"*\n" +
	"\x14ConfigPushStrRequest\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml\")\n" +
	"\x15ConfigPushStrResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"%\n" +
	"\x11ConfigPullRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"&\n" +
	"\x12ConfigPullResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"\"\n" +
	"\x0eFsWriteRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"#\n" +
	"\x0fFsWriteResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"!\n" +
	"\rFsListRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"\"\n" +
	"\x0eFsListResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"!\n" +
	"\rFsReadRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"\"\n" +
	"\x0eFsReadResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"(\n" +
	"\x14ResourcesListRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\")\n" +
	"\x15ResourcesListResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"'\n" +
	"\x13ResourcesGetRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"(\n" +
	"\x14ResourcesGetResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"0\n" +
	"\x1cResourcesReconcileNowRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"1\n" +
	"\x1dResourcesReconcileNowResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"/\n" +
	"\x1bResourcesForceDeleteRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"0\n" +
	"\x1cResourcesForceDeleteResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"'\n" +
	"\x13SystemRebootRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"(\n" +
	"\x14SystemRebootResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw2\xc8\t\n" +
	"\n" +
	"ApiService\x12i\n" +
	"\x0eConfigValidate\x12).containeros.api.v1.ConfigValidateRequest\x1a*.containeros.api.v1.ConfigValidateResponse\"\x00\x12]\n" +
	"\n" +
	"ConfigPush\x12%.containeros.api.v1.ConfigPushRequest\x1a&.containeros.api.v1.ConfigPushResponse\"\x00\x12f\n" +
	"\rConfigPushStr\x12(.containeros.api.v1.ConfigPushStrRequest\x1a).containeros.api.v1.ConfigPushStrResponse\"\x00\x12]\n" +
	"\n" +
	"ConfigPull\x12%.containeros.api.v1.ConfigPullRequest\x1a&.containeros.api.v1.ConfigPullResponse\"\x00\x12T\n" +
	"\aFsWrite\x12\".containeros.api.v1.FsWriteRequest\x1a#.containeros.api.v1.FsWriteResponse\"\x00\x12Q\n" +
	"\x06FsList\x12!.containeros.api.v1.FsListRequest\x1a\".containeros.api.v1.FsListResponse\"\x00\x12Q\n" +
	"\x06FsRead\x12!.containeros.api.v1.FsReadRequest\x1a\".containeros.api.v1.FsReadResponse\"\x00\x12f\n" +
	"\rResourcesList\x12(.containeros.api.v1.ResourcesListRequest\x1a).containeros.api.v1.ResourcesListResponse\"\x00\x12c\n" +
	"\fResourcesGet\x12'.containeros.api.v1.ResourcesGetRequest\x1a(.containeros.api.v1.ResourcesGetResponse\"\x00\x12~\n" +
	"\x15ResourcesReconcileNow\x120.containeros.api.v1.ResourcesReconcileNowRequest\x1a1.containeros.api.v1.ResourcesReconcileNowResponse\"\x00\x12{\n" +
	"\x14ResourcesForceDelete\x12/.containeros.api.v1.ResourcesForceDeleteRequest\x1a0.containeros.api.v1.ResourcesForceDeleteResponse\"\x00\x12c\n" +
	"\fSystemReboot\x12'.containeros.api.v1.SystemRebootRequest\x1a(.containeros.api.v1.SystemRebootResponse\"\x00B-Z+terraform-provider-containeros/internal/rpcb\x06proto3"

var (
	file_proto_containeros_api_v1_service_proto_rawDescOnce sync.Once
	file_proto_containeros_api_v1_service_proto_rawDescData []byte
)

func file_proto_containeros_api_v1_service_proto_rawDescGZIP() []byte {
	file_proto_containeros_api_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_containeros_api_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_containeros_api_v1_service_proto_rawDesc), len(file_proto_containeros_api_v1_service_proto_rawDesc)))
	})
	return file_proto_containeros_api_v1_service_proto_rawDescData
}

var file_proto_containeros_api_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_containeros_api_v1_service_proto_goTypes = []any{
	(*ConfigValidateRequest)(nil),         // 0: containeros.api.v1.ConfigValidateRequest
	(*ConfigValidateResponse)(nil),        // 1: containeros.api.v1.ConfigValidateResponse
	(*ConfigPushRequest)(nil),             // 2: containeros.api.v1.ConfigPushRequest
	(*ConfigPushResponse)(nil),            // 3: containeros.api.v1.ConfigPushResponse
	(*ConfigPushStrRequest)(nil),          // 4: containeros.api.v1.ConfigPushStrRequest
	(*ConfigPushStrResponse)(nil),         // 5: containeros.api.v1.ConfigPushStrResponse
	(*ConfigPullRequest)(nil),             // 6: containeros.api.v1.ConfigPullRequest
	(*ConfigPullResponse)(nil),            // 7: containeros.api.v1.ConfigPullResponse
	(*FsWriteRequest)(nil),                // 8: containeros.api.v1.FsWriteRequest
	(*FsWriteResponse)(nil),               // 9: containeros.api.v1.FsWriteResponse
	(*FsListRequest)(nil),                 // 10: containeros.api.v1.FsListRequest
	(*FsListResponse)(nil),                // 11: containeros.api.v1.FsListResponse
	(*FsReadRequest)(nil),                 // 12: containeros.api.v1.FsReadRequest
	(*FsReadResponse)(nil),                // 13: containeros.api.v1.FsReadResponse
	(*ResourcesListRequest)(nil),          // 14: containeros.api.v1.ResourcesListRequest
	(*ResourcesListResponse)(nil),         // 15: containeros.api.v1.ResourcesListResponse
	(*ResourcesGetRequest)(nil),           // 16: containeros.api.v1.ResourcesGetRequest
	(*ResourcesGetResponse)(nil),          // 17: containeros.api.v1.ResourcesGetResponse
	(*ResourcesReconcileNowRequest)(nil),  // 18: containeros.api.v1.ResourcesReconcileNowRequest
	(*ResourcesReconcileNowResponse)(nil), // 19: containeros.api.v1.ResourcesReconcileNowResponse
	(*ResourcesForceDeleteRequest)(nil),   // 20: containeros.api.v1.ResourcesForceDeleteRequest
	(*ResourcesForceDeleteResponse)(nil),  // 21: containeros.api.v1.ResourcesForceDeleteResponse
	(*SystemRebootRequest)(nil),           // 22: containeros.api.v1.SystemRebootRequest
	(*SystemRebootResponse)(nil),          // 23: containeros.api.v1.SystemRebootResponse
}
var file_proto_containeros_api_v1_service_proto_depIdxs = []int32{
	0,  // 0: containeros.api.v1.ApiService.ConfigValidate:input_type -> containeros.api.v1.ConfigValidateRequest
	2,  // 1: containeros.api.v1.ApiService.ConfigPush:input_type -> containeros.api.v1.ConfigPushRequest
	4,  // 2: containeros.api.v1.ApiService.ConfigPushStr:input_type -> containeros.api.v1.ConfigPushStrRequest
	6,  // 3: containeros.api.v1.ApiService.ConfigPull:input_type -> containeros.api.v1.ConfigPullRequest
	8,  // 4: containeros.api.v1.ApiService.FsWrite:input_type -> containeros.api.v1.FsWriteRequest
	10, // 5: containeros.api.v1.ApiService.FsList:input_type -> containeros.api.v1.FsListRequest
	12, // 6: containeros.api.v1.ApiService.FsRead:input_type -> containeros.api.v1.FsReadRequest
	14, // 7: containeros.api.v1.ApiService.ResourcesList:input_type -> containeros.api.v1.ResourcesListRequest
	16, // 8: containeros.api.v1.ApiService.ResourcesGet:input_type -> containeros.api.v1.ResourcesGetRequest
	18, // 9: containeros.api.v1.ApiService.ResourcesReconcileNow:input_type -> containeros.api.v1.ResourcesReconcileNowRequest
	20, // 10: containeros.api.v1.ApiService.ResourcesForceDelete:input_type -> containeros.api.v1.ResourcesForceDeleteRequest
	22, // 11: containeros.api.v1.ApiService.SystemReboot:input_type -> containeros.api.v1.SystemRebootRequest
	1,  // 12: containeros.api.v1.ApiService.ConfigValidate:output_type -> containeros.api.v1.ConfigValidateResponse
	3,  // 13: containeros.api.v1.ApiService.ConfigPush:output_type -> containeros.api.v1.ConfigPushResponse
	5,  // 14: containeros.api.v1.ApiService.ConfigPushStr:output_type -> containeros.api.v1.ConfigPushStrResponse
	7,  // 15: containeros.api.v1.ApiService.ConfigPull:output_type -> containeros.api.v1.ConfigPullResponse
	9,  // 16: containeros.api.v1.ApiService.FsWrite:output_type -> containeros.api.v1.FsWriteResponse
	11, // 17: containeros.api.v1.ApiService.FsList:output_type -> containeros.api.v1.FsListResponse
	13, // 18: containeros.api.v1.ApiService.FsRead:output_type -> containeros.api.v1.FsReadResponse
	15, // 19: containeros.api.v1.ApiService.ResourcesList:output_type -> containeros.api.v1.ResourcesListResponse
	17, // 20: containeros.api.v1.ApiService.ResourcesGet:output_type -> containeros.api.v1.ResourcesGetResponse
	19, // 21: containeros.api.v1.ApiService.ResourcesReconcileNow:output_type -> containeros.api.v1.ResourcesReconcileNowResponse
	21, // 22: containeros.api.v1.ApiService.ResourcesForceDelete:output_type -> containeros.api.v1.ResourcesForceDeleteResponse
	23, // 23: containeros.api.v1.ApiService.SystemReboot:output_type -> containeros.api.v1.SystemRebootResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_containeros_api_v1_service_proto_init() }
func file_proto_containeros_api_v1_service_proto_init() {
	if File_proto_containeros_api_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_containeros_api_v1_service_proto_rawDesc), len(file_proto_containeros_api_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_containeros_api_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_containeros_api_v1_service_proto_depIdxs,
		MessageInfos:      file_proto_containeros_api_v1_service_proto_msgTypes,
	}.Build()
	File_proto_containeros_api_v1_service_proto = out.File
	file_proto_containeros_api_v1_service_proto_goTypes = nil
	file_proto_containeros_api_v1_service_proto_depIdxs = nil
}
