// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: proto/containeros/api/v1/service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiService_ConfigValidate_FullMethodName        = "/containeros.api.v1.ApiService/ConfigValidate"
	ApiService_ConfigPush_FullMethodName            = "/containeros.api.v1.ApiService/ConfigPush"
	ApiService_ConfigPushStr_FullMethodName         = "/containeros.api.v1.ApiService/ConfigPushStr"
	ApiService_ConfigPull_FullMethodName            = "/containeros.api.v1.ApiService/ConfigPull"
	ApiService_FsWrite_FullMethodName               = "/containeros.api.v1.ApiService/FsWrite"
	ApiService_FsList_FullMethodName                = "/containeros.api.v1.ApiService/FsList"
	ApiService_FsRead_FullMethodName                = "/containeros.api.v1.ApiService/FsRead"
	ApiService_ResourcesList_FullMethodName         = "/containeros.api.v1.ApiService/ResourcesList"
	ApiService_ResourcesGet_FullMethodName          = "/containeros.api.v1.ApiService/ResourcesGet"
	ApiService_ResourcesReconcileNow_FullMethodName = "/containeros.api.v1.ApiService/ResourcesReconcileNow"
	ApiService_ResourcesForceDelete_FullMethodName  = "/containeros.api.v1.ApiService/ResourcesForceDelete"
	ApiService_SystemReboot_FullMethodName          = "/containeros.api.v1.ApiService/SystemReboot"
)

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiServiceClient interface {
	ConfigValidate(ctx context.Context, in *ConfigValidateRequest, opts ...grpc.CallOption) (*ConfigValidateResponse, error)
	ConfigPush(ctx context.Context, in *ConfigPushRequest, opts ...grpc.CallOption) (*ConfigPushResponse, error)
	ConfigPushStr(ctx context.Context, in *ConfigPushStrRequest, opts ...grpc.CallOption) (*ConfigPushStrResponse, error)
	ConfigPull(ctx context.Context, in *ConfigPullRequest, opts ...grpc.CallOption) (*ConfigPullResponse, error)
	FsWrite(ctx context.Context, in *FsWriteRequest, opts ...grpc.CallOption) (*FsWriteResponse, error)
	FsList(ctx context.Context, in *FsListRequest, opts ...grpc.CallOption) (*FsListResponse, error)
	FsRead(ctx context.Context, in *FsReadRequest, opts ...grpc.CallOption) (*FsReadResponse, error)
	ResourcesList(ctx context.Context, in *ResourcesListRequest, opts ...grpc.CallOption) (*ResourcesListResponse, error)
	ResourcesGet(ctx context.Context, in *ResourcesGetRequest, opts ...grpc.CallOption) (*ResourcesGetResponse, error)
	ResourcesReconcileNow(ctx context.Context, in *ResourcesReconcileNowRequest, opts ...grpc.CallOption) (*ResourcesReconcileNowResponse, error)
	ResourcesForceDelete(ctx context.Context, in *ResourcesForceDeleteRequest, opts ...grpc.CallOption) (*ResourcesForceDeleteResponse, error)
	SystemReboot(ctx context.Context, in *SystemRebootRequest, opts ...grpc.CallOption) (*SystemRebootResponse, error)
}

type apiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiServiceClient(cc grpc.ClientConnInterface) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) ConfigValidate(ctx context.Context, in *ConfigValidateRequest, opts ...grpc.CallOption) (*ConfigValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigValidateResponse)
	err := c.cc.Invoke(ctx, ApiService_ConfigValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ConfigPush(ctx context.Context, in *ConfigPushRequest, opts ...grpc.CallOption) (*ConfigPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigPushResponse)
	err := c.cc.Invoke(ctx, ApiService_ConfigPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ConfigPushStr(ctx context.Context, in *ConfigPushStrRequest, opts ...grpc.CallOption) (*ConfigPushStrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigPushStrResponse)
	err := c.cc.Invoke(ctx, ApiService_ConfigPushStr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ConfigPull(ctx context.Context, in *ConfigPullRequest, opts ...grpc.CallOption) (*ConfigPullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigPullResponse)
	err := c.cc.Invoke(ctx, ApiService_ConfigPull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) FsWrite(ctx context.Context, in *FsWriteRequest, opts ...grpc.CallOption) (*FsWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FsWriteResponse)
	err := c.cc.Invoke(ctx, ApiService_FsWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) FsList(ctx context.Context, in *FsListRequest, opts ...grpc.CallOption) (*FsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FsListResponse)
	err := c.cc.Invoke(ctx, ApiService_FsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) FsRead(ctx context.Context, in *FsReadRequest, opts ...grpc.CallOption) (*FsReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FsReadResponse)
	err := c.cc.Invoke(ctx, ApiService_FsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ResourcesList(ctx context.Context, in *ResourcesListRequest, opts ...grpc.CallOption) (*ResourcesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesListResponse)
	err := c.cc.Invoke(ctx, ApiService_ResourcesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ResourcesGet(ctx context.Context, in *ResourcesGetRequest, opts ...grpc.CallOption) (*ResourcesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesGetResponse)
	err := c.cc.Invoke(ctx, ApiService_ResourcesGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ResourcesReconcileNow(ctx context.Context, in *ResourcesReconcileNowRequest, opts ...grpc.CallOption) (*ResourcesReconcileNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesReconcileNowResponse)
	err := c.cc.Invoke(ctx, ApiService_ResourcesReconcileNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ResourcesForceDelete(ctx context.Context, in *ResourcesForceDeleteRequest, opts ...grpc.CallOption) (*ResourcesForceDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesForceDeleteResponse)
	err := c.cc.Invoke(ctx, ApiService_ResourcesForceDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) SystemReboot(ctx context.Context, in *SystemRebootRequest, opts ...grpc.CallOption) (*SystemRebootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemRebootResponse)
	err := c.cc.Invoke(ctx, ApiService_SystemReboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
// All implementations must embed UnimplementedApiServiceServer
// for forward compatibility.
type ApiServiceServer interface {
	ConfigValidate(context.Context, *ConfigValidateRequest) (*ConfigValidateResponse, error)
	ConfigPush(context.Context, *ConfigPushRequest) (*ConfigPushResponse, error)
	ConfigPushStr(context.Context, *ConfigPushStrRequest) (*ConfigPushStrResponse, error)
	ConfigPull(context.Context, *ConfigPullRequest) (*ConfigPullResponse, error)
	FsWrite(context.Context, *FsWriteRequest) (*FsWriteResponse, error)
	FsList(context.Context, *FsListRequest) (*FsListResponse, error)
	FsRead(context.Context, *FsReadRequest) (*FsReadResponse, error)
	ResourcesList(context.Context, *ResourcesListRequest) (*ResourcesListResponse, error)
	ResourcesGet(context.Context, *ResourcesGetRequest) (*ResourcesGetResponse, error)
	ResourcesReconcileNow(context.Context, *ResourcesReconcileNowRequest) (*ResourcesReconcileNowResponse, error)
	ResourcesForceDelete(context.Context, *ResourcesForceDeleteRequest) (*ResourcesForceDeleteResponse, error)
	SystemReboot(context.Context, *SystemRebootRequest) (*SystemRebootResponse, error)
	mustEmbedUnimplementedApiServiceServer()
}

// UnimplementedApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServiceServer struct{}

func (UnimplementedApiServiceServer) ConfigValidate(context.Context, *ConfigValidateRequest) (*ConfigValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigValidate not implemented")
}
func (UnimplementedApiServiceServer) ConfigPush(context.Context, *ConfigPushRequest) (*ConfigPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigPush not implemented")
}
func (UnimplementedApiServiceServer) ConfigPushStr(context.Context, *ConfigPushStrRequest) (*ConfigPushStrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigPushStr not implemented")
}
func (UnimplementedApiServiceServer) ConfigPull(context.Context, *ConfigPullRequest) (*ConfigPullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigPull not implemented")
}
func (UnimplementedApiServiceServer) FsWrite(context.Context, *FsWriteRequest) (*FsWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FsWrite not implemented")
}
func (UnimplementedApiServiceServer) FsList(context.Context, *FsListRequest) (*FsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FsList not implemented")
}
func (UnimplementedApiServiceServer) FsRead(context.Context, *FsReadRequest) (*FsReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FsRead not implemented")
}
func (UnimplementedApiServiceServer) ResourcesList(context.Context, *ResourcesListRequest) (*ResourcesListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourcesList not implemented")
}
func (UnimplementedApiServiceServer) ResourcesGet(context.Context, *ResourcesGetRequest) (*ResourcesGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourcesGet not implemented")
}
func (UnimplementedApiServiceServer) ResourcesReconcileNow(context.Context, *ResourcesReconcileNowRequest) (*ResourcesReconcileNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourcesReconcileNow not implemented")
}
func (UnimplementedApiServiceServer) ResourcesForceDelete(context.Context, *ResourcesForceDeleteRequest) (*ResourcesForceDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourcesForceDelete not implemented")
}
func (UnimplementedApiServiceServer) SystemReboot(context.Context, *SystemRebootRequest) (*SystemRebootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemReboot not implemented")
}
func (UnimplementedApiServiceServer) mustEmbedUnimplementedApiServiceServer() {}
func (UnimplementedApiServiceServer) testEmbeddedByValue()                    {}

// UnsafeApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServiceServer will
// result in compilation errors.
type UnsafeApiServiceServer interface {
	mustEmbedUnimplementedApiServiceServer()
}

func RegisterApiServiceServer(s grpc.ServiceRegistrar, srv ApiServiceServer) {
	// If the following call panics, it indicates UnimplementedApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiService_ServiceDesc, srv)
}

func _ApiService_ConfigValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ConfigValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ConfigValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ConfigValidate(ctx, req.(*ConfigValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ConfigPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ConfigPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ConfigPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ConfigPush(ctx, req.(*ConfigPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ConfigPushStr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPushStrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ConfigPushStr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ConfigPushStr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ConfigPushStr(ctx, req.(*ConfigPushStrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ConfigPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ConfigPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ConfigPull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ConfigPull(ctx, req.(*ConfigPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_FsWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FsWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).FsWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_FsWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).FsWrite(ctx, req.(*FsWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_FsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).FsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_FsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).FsList(ctx, req.(*FsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_FsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).FsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_FsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).FsRead(ctx, req.(*FsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ResourcesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ResourcesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ResourcesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ResourcesList(ctx, req.(*ResourcesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ResourcesGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ResourcesGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ResourcesGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ResourcesGet(ctx, req.(*ResourcesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ResourcesReconcileNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesReconcileNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ResourcesReconcileNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ResourcesReconcileNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ResourcesReconcileNow(ctx, req.(*ResourcesReconcileNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ResourcesForceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesForceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ResourcesForceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ResourcesForceDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ResourcesForceDelete(ctx, req.(*ResourcesForceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_SystemReboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemRebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).SystemReboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_SystemReboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).SystemReboot(ctx, req.(*SystemRebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiService_ServiceDesc is the grpc.ServiceDesc for ApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containeros.api.v1.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigValidate",
			Handler:    _ApiService_ConfigValidate_Handler,
		},
		{
			MethodName: "ConfigPush",
			Handler:    _ApiService_ConfigPush_Handler,
		},
		{
			MethodName: "ConfigPushStr",
			Handler:    _ApiService_ConfigPushStr_Handler,
		},
		{
			MethodName: "ConfigPull",
			Handler:    _ApiService_ConfigPull_Handler,
		},
		{
			MethodName: "FsWrite",
			Handler:    _ApiService_FsWrite_Handler,
		},
		{
			MethodName: "FsList",
			Handler:    _ApiService_FsList_Handler,
		},
		{
			MethodName: "FsRead",
			Handler:    _ApiService_FsRead_Handler,
		},
		{
			MethodName: "ResourcesList",
			Handler:    _ApiService_ResourcesList_Handler,
		},
		{
			MethodName: "ResourcesGet",
			Handler:    _ApiService_ResourcesGet_Handler,
		},
		{
			MethodName: "ResourcesReconcileNow",
			Handler:    _ApiService_ResourcesReconcileNow_Handler,
		},
		{
			MethodName: "ResourcesForceDelete",
			Handler:    _ApiService_ResourcesForceDelete_Handler,
		},
		{
			MethodName: "SystemReboot",
			Handler:    _ApiService_SystemReboot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/containeros/api/v1/service.proto",
}
