@startuml C4_Container
!NEW_C4_STYLE=1
    !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

title ContainerOS - Operating System - Container View
UpdateSystemBoundaryStyle($fontColor=$SYSTEM_BG_COLOR, $type="Software System")

System_Boundary(system, "ContainerOS System") {
    Container(supervisor, "supervisor", "Rust", "Starts and monitors all the managers")
    Container(api, "API", "Rust", "External entrypoint of the OS")
    Container(state, "State Manager", "Rust", "Orchestrates all reconciliations")
    Container(sys, "System Manager", "Rust", "Manages system settings, files, ...")
    Container(container, "Container Manager", "Rust", "Manages containers and their volumes, networks, ...")
    Container(network, "Network Manager", "Rust", "Manages network interfaces, DNS, NTP, ...")
    Container(storage, "Storage Manager", "Rust", "Manages disk partitioning, additional mounts, ...")
    ' Container_Ext(kernel, "Kernel", "Linux")

    Container_Ext(container_runtime, "Container Runtime", "Podman")
    Container_Ext(dhcp, "DHCP client", "dhcpd")
    Container_Ext(ntp, "NTP client", "ntpd")
    ' Container_Ext(disk, "Persistent Storage", "HDD/SDD")

    Rel(supervisor, api, "Control channel", "Unix Domain Socket")
    Rel(supervisor, state, "Control channel", "Unix Domain Socket")

    Rel(api, state, "")

    Rel(state, sys, "Schedules reconciliation", "gRPC")
    Rel(state, container, "")
    Rel(state, network, "")
    ' Rel(state, storage, "")

    ' Rel(storage, disk, "")
    Rel(container, container_runtime, "")
    Rel(network, ntp, "")
    Rel(network, dhcp, "")
    ' Rel(network, kernel, "", "rtnetlink")
    ' Rel(supervisor, kernel, "")
}

@enduml
