#!/usr/bin/env -S just --justfile

set dotenv-load

cargo-cmd := "cargo"
cargo-args := "--all-targets --all-features"

@help:
    just --list

check:
    {{ cargo-cmd }} fmt --all --check
    {{ cargo-cmd }} clippy {{ cargo-args }} --future-incompat-report

fix:
    {{ cargo-cmd }} fmt --all
    {{ cargo-cmd }} clippy {{ cargo-args }} --fix --allow-dirty

build:

clean:
    {{ cargo-cmd }} clean


test: test-doc test-unit test-integration

test-doc:
    cargo test --doc

test-unit:
    cargo nextest run -E '(kind(lib) or kind(bin)) and not package(e2e)'

test-integration:
    cargo nextest run -E 'kind(test) and not package(e2e)'

rebuild-proto:
    {{ cargo-cmd }} clean -p cos-proto-reconciler -p cos-proto-reconciler-server -p cos-proto-reconciler-client
    {{ cargo-cmd }} check -p cos-proto-reconciler
    {{ cargo-cmd }} check -p cos-proto-reconciler-server
    {{ cargo-cmd }} check -p cos-proto-reconciler-client
