syntax = "proto3";

package containeros.reconciler.v1;

import "containeros/shared/v1/shared.proto";

service ReconcilerService {
  // rpc ValidateResource, DeleteResource, Plan

  // GUARANTEES:
  // - CreateDynamicResource is always the first call made for any given resource.
  // - CreateDynamicResource is retried rescheduled until it returns a gRPC-level success response. A gRPC error will
  //   never advance the resource past this stage.
  // - At most one concurrent call to either Create or Reconcile will be made per service.
  rpc CreateDynamicResource(CreateDynamicResourceRequest) returns (CreateDynamicResourceResponse) {}
  rpc ReconcileDynamicResource(ReconcileDynamicResourceRequest) returns (ReconcileDynamicResourceResponse) {}
}

// message StatePending {
//   bytes state = 1;
// }

// message StateCompleted {
//   bytes state = 1;
// }

// message StateSuspended {
//   bytes state = 1;
//   string reason = 2;
// }

message CreateDynamicResourceRequest {
  containeros.shared.v1.Identity id = 1;
  // containeros.shared.v1.Identity owner = 2;
  bytes spec = 3;
}

message CreateDynamicResourceResponse {
  message StateReady {
    bytes state = 1;
  }

  message StateError {
    bytes state = 1;
    string reason = 2;
  }

  oneof state {
    // StatePending pending = 1;
    StateReady ready = 2;
    // StateCompleted completed = 3;
    // StateSuspended suspended = 4;
    StateError error = 5;
  }
}

message ReconcileDynamicResourceRequest {
  message StateReady {
    bytes state = 1;
  }

  message StateError {
    bytes state = 1;
  }

  oneof state {
    // StatePending pending = 1;
    StateReady ready = 2;
    // StateCompleted completed = 3;
    // StateSuspended suspended = 4;
    StateError error = 5;
  }

  containeros.shared.v1.Identity id = 6;
  bytes spec = 7;
}

message ReconcileDynamicResourceResponse {
  message StateReady {
    bytes state = 1;
  }

  message StateError {
    bytes state = 1;
    string reason = 2;
  }

  oneof state {
    // StatePending pending = 1;
    StateReady ready = 2;
    // StateCompleted completed = 3;
    // StateSuspended suspended = 4;
    StateError error = 5;
  }
}
