syntax = "proto3";

package containeros.reconciler.v1;

import "google/protobuf/empty.proto";

service ReconcilerService {
  // rpc ValidateResource, DeleteResource, Plan

  // GUARANTEES:
  // - CreateXYZ is always the first call made for any given resource.
  // - CreateXYZ is retried rescheduled until it returns a gRPC-level success response. A gRPC error will
  //   never advance the resource past this stage.
  // - At most one concurrent call to either Create or Reconcile will be made per service.

  rpc ReconcileUserConfig(ReconcileUserConfigRequest) returns (ReconcileUserConfigResponse) {}
  rpc ReconcileDynamicResource(ReconcileDynamicResourceRequest) returns (ReconcileDynamicResourceResponse) {}
}

message Identity {
  string schema = 1;
  string name = 2;
}

message DynamicResourceCreate {
  string schema = 1;
  string name = 2;
  bytes spec = 3;
}

message ReconcileUserConfigRequest {
  string schema = 1;
  string name = 2;
  bytes spec = 3;

  oneof state {
    google.protobuf.Empty unset = 4;
    bytes ready = 5;
  }

  repeated Identity children = 6;
}

message ReconcileUserConfigResponse {
  bytes state = 1;
  repeated DynamicResourceCreate create = 3;
}

message ReconcileDynamicResourceRequest {
  string schema = 1;
  string name = 2;
  bytes spec = 3;

  oneof state {
    google.protobuf.Empty unset = 4;
    bytes ready = 5;
  }

  repeated Identity children = 6;
  Identity owner = 7;
}

message ReconcileDynamicResourceResponse {
  bytes state = 1;
  repeated DynamicResourceCreate create = 3;
}
