#!/usr/bin/env -S just --justfile

set dotenv-load

[private]
_docker := env("JUST_CONTAINER_RUNTIME", "docker")

[private]
_docker-args := "run --rm -v " + module_directory() + ":/work -w /work "

[private]
_docker-buf-image := "docker.io/bufbuild/buf:1.69.0@sha256:daa3bf554150247bc0d47f73fb8b355faa193dad5428aa1efcf74480e210ec40"

[private]
_buf-runner := _docker + " " + _docker-args + " " + _docker-buf-image

@help:
    just --list

check: format lint

fix: format-fix

[private]
ci-check: check

[private]
format:
    {{ _buf-runner }} format --diff --exit-code

[private]
format-fix:
    {{ _buf-runner }} format -w

[private]
lint:
    {{ _buf-runner }} lint

build:

clean:
