#!/usr/bin/env -S just --justfile

set dotenv-load

buf-bin := "buf"

@help:
    just --list

check:
    {{ buf-bin }} format --diff --exit-code
    {{ buf-bin }} lint

fix:
    {{ buf-bin }} format -w

build:

clean:
