[package]
name = "isolation"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
linux-utils.path = "../linux-utils"
isolation-macros.path = "../isolation-macros"
rustix = { workspace = true, features = ["param", "process"] }
nix = { workspace = true, features = ["sched", "process", "user", "fs"] }
tempfile.workspace = true

[dev-dependencies]
rtnetlink = { workspace = true, features = ["smol_socket"] }
smol.workspace = true
