#!/usr/bin/env -S just --justfile

set dotenv-load

cargo-cmd := "cargo"
cargo-args := "--all-targets --all-features"

@help:
    just --list

check:
    {{ cargo-cmd }} fmt --all --check
    {{ cargo-cmd }} clippy {{ cargo-args }} --future-incompat-report

[private]
ci-check:
    {{ cargo-cmd }} fmt --all --check
    {{ cargo-cmd }} clippy {{ cargo-args }} --future-incompat-report -- -D warnings

fix:
    {{ cargo-cmd }} fmt --all
    {{ cargo-cmd }} clippy {{ cargo-args }} --future-incompat-report --fix --allow-dirty

build:

clean:
    {{ cargo-cmd }} clean

rebuild-proto:
    {{ cargo-cmd }} clean -p cos-api-reconciler -p cos-api-reconciler-server -p cos-api-reconciler-client
    {{ cargo-cmd }} check -p cos-api-reconciler
    {{ cargo-cmd }} check -p cos-api-reconciler-server
    {{ cargo-cmd }} check -p cos-api-reconciler-client
