[package]
name = "state-manager"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["std", "derive"] }
cos-proto-reconciler.path = "../../crates/cos-proto-reconciler"
cos-proto-reconciler-client.path = "../../crates/cos-proto-reconciler-client"
cos-proto-state.path = "../../crates/cos-proto-state"
cos-proto-state-server.path = "../../crates/cos-proto-state-server"
network-controller.path = "../network-controller"
container-controller.path = "../container-controller"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal",] }
tokio-util.workspace = true
tonic = { workspace = true, features = ["channel"] }
serde_json = { workspace = true, features = ["std"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["std", "fmt", "ansi", "env-filter"] }
itertools = { workspace = true, features = ["use_std"] }
thiserror.workspace = true
