---
machine:
  certSANs:
    - 10.0.2.15
    - 127.0.0.1
    - localhost
    - "[::1]"
  features:
    kubePrism:
      enabled: false
  pods:
    - apiVersion: v1
      kind: Pod
      metadata:
        name: probe
      spec:
        containers:
          - name: probe
            image: docker.io/alpine/curl:latest
            args: [http://10.0.2.2:1234]
cluster:
  network:
    cni:
      name: flannel
