[package]
name = "cosc"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["std", "derive"] }
cos-proto-reconciler.path = "../../crates/cos-proto-reconciler"
cos-proto-api.path = "../../crates/cos-proto-api"
cos-proto-api-client.path = "../../crates/cos-proto-api-client"
tokio = { workspace = true, features = ["macros", "rt"] }
tonic = { workspace = true, features = ["channel"] }
serde_json = { workspace = true, features = ["std"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = [
    "std",
    "fmt",
    "ansi",
    "env-filter",
] }
itertools = { workspace = true, features = ["use_std"] }
clap = { workspace = true, features = ["derive"] }
serde_yaml.workspace = true
