[package]
name = "cosc"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
clap.workspace = true
cos-api-api-client.path = "../../crates/cos-api-api-client"
cos-api-api.path = "../../crates/cos-api-api"
tokio.workspace = true
tonic.workspace = true
rmpv.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_yaml.workspace = true
